import { Asset } from "@global components/layout/fileUploader";
import { GCSFileMetadata } from "../../../global components/layout/fileUploader/types/assets.types";

// SAMPLE PROCESSED ASSETS - Ready for UI Rendering
export const sampleProcessedAssets: Asset[] = [
  // Website Assets
  {
    id: "1738945800000",
    name: "hero-background.jpg",
    type: "image",
    size: "3.2 MB",
    usage: "Homepage Hero Section",
    uploadDate: "2026-01-15",
    url: "https://firebasestorage.googleapis.com/...",
    fullPath: "home page/hero-background.jpg",
    category: "website",
    contentType: "image/jpeg",
  },
  {
    id: "1738945801000",
    name: "experience-team.jpg",
    type: "image",
    size: "2.8 MB",
    usage: "Homepage Experience Section",
    uploadDate: "2026-01-16",
    url: "https://firebasestorage.googleapis.com/...",
    fullPath: "home page/experience-team.jpg",
    category: "website",
    contentType: "image/jpeg",
  },

  // Project Assets
  {
    id: "1738945803000",
    name: "hero-image.jpg",
    type: "image",
    size: "3.5 MB",
    usage: "Metro Bridge Project - Hero Image",
    uploadDate: "2026-01-10",
    url: "https://firebasestorage.googleapis.com/...",
    fullPath: "projects/metro-bridge/hero-image.jpg",
    category: "projects",
    contentType: "image/jpeg",
  },
  {
    id: "1738945804000",
    name: "blueprint.pdf",
    type: "document",
    size: "5.1 MB",
    usage: "Metro Bridge Project - Technical Blueprint",
    uploadDate: "2026-01-12",
    url: "https://firebasestorage.googleapis.com/...",
    fullPath: "projects/metro-bridge/blueprint.pdf",
    category: "projects",
    contentType: "application/pdf",
  },
  {
    id: "1738945805000",
    name: "phase-1.jpg",
    type: "image",
    size: "4.2 MB",
    usage: "Metro Bridge Project - Phase 1 Progress",
    uploadDate: "2026-01-14",
    url: "https://firebasestorage.googleapis.com/...",
    fullPath: "projects/metro-bridge/progress-photos/phase-1.jpg",
    category: "projects",
    contentType: "image/jpeg",
  },
  {
    id: "1738945806000",
    name: "diagram.svg",
    type: "diagram",
    size: "512 KB",
    usage: "Solar Farm Project - System Diagram",
    uploadDate: "2026-01-18",
    url: "https://firebasestorage.googleapis.com/...",
    fullPath: "projects/solar-farm/diagram.svg",
    category: "projects",
    contentType: "image/svg+xml",
  },

  // Branding Assets
  {
    id: "1738945807000",
    name: "logo-primary.svg",
    type: "diagram",
    size: "156 KB",
    usage: "Primary Company Logo",
    uploadDate: "2026-01-05",
    url: "https://firebasestorage.googleapis.com/...",
    fullPath: "branding/logo-primary.svg",
    category: "branding",
    contentType: "image/svg+xml",
  },
  {
    id: "1738945808000",
    name: "logo-white.png",
    type: "image",
    size: "89 KB",
    usage: "Logo for Dark Backgrounds",
    uploadDate: "2026-01-05",
    url: "https://firebasestorage.googleapis.com/...",
    fullPath: "branding/logo-white.png",
    category: "branding",
    contentType: "image/png",
  },
  {
    id: "1738945809000",
    name: "brand-guidelines.pdf",
    type: "document",
    size: "2.3 MB",
    usage: "Brand Guidelines and Standards",
    uploadDate: "2026-01-06",
    url: "https://firebasestorage.googleapis.com/...",
    fullPath: "branding/brand-guidelines.pdf",
    category: "branding",
    contentType: "application/pdf",
  },

  // Service Icons
  {
    id: "1738945810000",
    name: "structural-engineering-icon.svg",
    type: "diagram",
    size: "42 KB",
    usage: "Service Icon - Structural Engineering",
    uploadDate: "2026-01-20",
    url: "https://firebasestorage.googleapis.com/...",
    fullPath: "services/structural-engineering-icon.svg",
    category: "services",
    contentType: "image/svg+xml",
  },
  {
    id: "1738945811000",
    name: "electrical-systems-icon.svg",
    type: "diagram",
    size: "38 KB",
    usage: "Service Icon - Electrical Systems",
    uploadDate: "2026-01-20",
    url: "https://firebasestorage.googleapis.com/...",
    fullPath: "services/electrical-systems-icon.svg",
    category: "services",
    contentType: "image/svg+xml",
  },

  // Certificates
  {
    id: "1738945812000",
    name: "iso-certification.pdf",
    type: "document",
    size: "1.8 MB",
    usage: "ISO 9001 Certification",
    uploadDate: "2026-01-08",
    url: "https://firebasestorage.googleapis.com/...",
    fullPath: "certificates/iso-certification.pdf",
    category: "certificates",
    contentType: "application/pdf",
  },

  // Documentation
  {
    id: "1738945813000",
    name: "company-profile.pdf",
    type: "document",
    size: "3.4 MB",
    usage: "Company Profile Document",
    uploadDate: "2026-01-03",
    url: "https://firebasestorage.googleapis.com/...",
    fullPath: "documents/company-profile.pdf",
    category: "documents",
    contentType: "application/pdf",
  },
  {
    id: "1738945814000",
    name: "capabilities-statement.pdf",
    type: "document",
    size: "2.9 MB",
    usage: "Capabilities Statement",
    uploadDate: "2026-01-03",
    url: "https://firebasestorage.googleapis.com/...",
    fullPath: "documents/capabilities-statement.pdf",
    category: "documents",
    contentType: "application/pdf",
  },
];

// RAW GCS METADATA - Before transformation
export const sampleRawGCSFiles: GCSFileMetadata[] = [
  // Website Assets
  {
    name: "website/homepage/hero-background.jpg",
    bucket: "ptr-command-center-assets",
    generation: "1738945800000",
    metageneration: "1",
    contentType: "image/jpeg",
    timeCreated: "2026-01-15T10:30:00.000Z",
    updated: "2026-01-15T10:30:00.000Z",
    storageClass: "STANDARD",
    size: "3355443", // 3.2 MB in bytes
    md5Hash: "a1b2c3d4e5f6...",
    mediaLink: "https://firebasestorage.googleapis.com/...",
    metadata: {
      usage: "Homepage Hero Section",
      category: "website",
      tags: "hero,homepage,background",
      usedIn: "homepage-hero",
    },
  },
  {
    name: "website/homepage/experience-team.jpg",
    bucket: "ptr-command-center-assets",
    generation: "1738945801000",
    metageneration: "1",
    contentType: "image/jpeg",
    timeCreated: "2026-01-16T14:20:00.000Z",
    updated: "2026-01-16T14:20:00.000Z",
    storageClass: "STANDARD",
    size: "2936012", // 2.8 MB in bytes
    md5Hash: "f6e5d4c3b2a1...",
    mediaLink: "https://firebasestorage.googleapis.com/...",
    metadata: {
      usage: "Homepage Experience Section",
      category: "website",
      tags: "team,experience,homepage",
      usedIn: "homepage-experience",
    },
  },
  {
    name: "website/about/overview-banner.jpg",
    bucket: "ptr-command-center-assets",
    generation: "1738945802000",
    metageneration: "1",
    contentType: "image/jpeg",
    timeCreated: "2026-01-17T09:15:00.000Z",
    updated: "2026-01-17T09:15:00.000Z",
    storageClass: "STANDARD",
    size: "2621440", // 2.5 MB in bytes
    md5Hash: "1a2b3c4d5e6f...",
    mediaLink: "https://firebasestorage.googleapis.com/...",
    metadata: {
      usage: "About Page Banner",
      category: "website",
      tags: "about,banner,overview",
      usedIn: "about-page-banner",
    },
  },

  // Project Assets
  {
    name: "projects/metro-bridge/hero-image.jpg",
    bucket: "ptr-command-center-assets",
    generation: "1738945803000",
    metageneration: "1",
    contentType: "image/jpeg",
    timeCreated: "2026-01-10T16:45:00.000Z",
    updated: "2026-01-10T16:45:00.000Z",
    storageClass: "STANDARD",
    size: "3670016", // 3.5 MB in bytes
    md5Hash: "6f5e4d3c2b1a...",
    mediaLink: "https://firebasestorage.googleapis.com/...",
    metadata: {
      usage: "Metro Bridge Project - Hero Image",
      category: "projects",
      tags: "bridge,metro,hero,featured",
      usedIn: "project-detail-metro-bridge",
    },
  },
  {
    name: "projects/metro-bridge/blueprint.pdf",
    bucket: "ptr-command-center-assets",
    generation: "1738945804000",
    metageneration: "1",
    contentType: "application/pdf",
    timeCreated: "2026-01-12T11:30:00.000Z",
    updated: "2026-01-12T11:30:00.000Z",
    storageClass: "STANDARD",
    size: "5347737", // 5.1 MB in bytes
    md5Hash: "a0b1c2d3e4f5...",
    mediaLink: "https://firebasestorage.googleapis.com/...",
    metadata: {
      usage: "Metro Bridge Project - Technical Blueprint",
      category: "projects",
      tags: "blueprint,technical,metro-bridge",
      usedIn: "project-documents-metro-bridge",
    },
  },
  {
    name: "projects/metro-bridge/progress-photos/phase-1.jpg",
    bucket: "ptr-command-center-assets",
    generation: "1738945805000",
    metageneration: "1",
    contentType: "image/jpeg",
    timeCreated: "2026-01-14T13:20:00.000Z",
    updated: "2026-01-14T13:20:00.000Z",
    storageClass: "STANDARD",
    size: "4404019", // 4.2 MB in bytes
    md5Hash: "5f4e3d2c1b0a...",
    mediaLink: "https://firebasestorage.googleapis.com/...",
    metadata: {
      usage: "Metro Bridge Project - Phase 1 Progress",
      category: "projects",
      tags: "progress,phase1,construction,metro-bridge",
      usedIn: "project-gallery-metro-bridge",
    },
  },
  {
    name: "projects/solar-farm/diagram.svg",
    bucket: "ptr-command-center-assets",
    generation: "1738945806000",
    metageneration: "1",
    contentType: "image/svg+xml",
    timeCreated: "2026-01-18T08:45:00.000Z",
    updated: "2026-01-18T08:45:00.000Z",
    storageClass: "STANDARD",
    size: "524288", // 512 KB in bytes
    md5Hash: "0a1b2c3d4e5f...",
    mediaLink: "https://firebasestorage.googleapis.com/...",
    metadata: {
      usage: "Solar Farm Project - System Diagram",
      category: "projects",
      tags: "diagram,solar,technical",
      usedIn: "project-detail-solar-farm",
    },
  },

  // Branding Assets
  {
    name: "branding/logo-primary.svg",
    bucket: "ptr-command-center-assets",
    generation: "1738945807000",
    metageneration: "1",
    contentType: "image/svg+xml",
    timeCreated: "2026-01-05T12:00:00.000Z",
    updated: "2026-01-05T12:00:00.000Z",
    storageClass: "STANDARD",
    size: "159744", // 156 KB in bytes
    md5Hash: "f0e1d2c3b4a5...",
    mediaLink: "https://firebasestorage.googleapis.com/...",
    metadata: {
      usage: "Primary Company Logo",
      category: "branding",
      tags: "logo,primary,brand",
      usedIn: "header,footer,documents",
    },
  },
  {
    name: "branding/logo-white.png",
    bucket: "ptr-command-center-assets",
    generation: "1738945808000",
    metageneration: "1",
    contentType: "image/png",
    timeCreated: "2026-01-05T12:15:00.000Z",
    updated: "2026-01-05T12:15:00.000Z",
    storageClass: "STANDARD",
    size: "91136", // 89 KB in bytes
    md5Hash: "6e5d4c3b2a19...",
    mediaLink: "https://firebasestorage.googleapis.com/...",
    metadata: {
      usage: "Logo for Dark Backgrounds",
      category: "branding",
      tags: "logo,white,dark-background",
      usedIn: "hero-section,footer-dark",
    },
  },
  {
    name: "branding/brand-guidelines.pdf",
    bucket: "ptr-command-center-assets",
    generation: "1738945809000",
    metageneration: "1",
    contentType: "application/pdf",
    timeCreated: "2026-01-06T10:30:00.000Z",
    updated: "2026-01-06T10:30:00.000Z",
    storageClass: "STANDARD",
    size: "2411724", // 2.3 MB in bytes
    md5Hash: "1f2e3d4c5b6a...",
    mediaLink: "https://firebasestorage.googleapis.com/...",
    metadata: {
      usage: "Brand Guidelines and Standards",
      category: "branding",
      tags: "guidelines,brand,standards",
      usedIn: "internal-reference",
    },
  },

  // Service Icons
  {
    name: "services/structural-engineering-icon.svg",
    bucket: "ptr-command-center-assets",
    generation: "1738945810000",
    metageneration: "1",
    contentType: "image/svg+xml",
    timeCreated: "2026-01-20T15:00:00.000Z",
    updated: "2026-01-20T15:00:00.000Z",
    storageClass: "STANDARD",
    size: "43008", // 42 KB in bytes
    md5Hash: "a9b8c7d6e5f4...",
    mediaLink: "https://firebasestorage.googleapis.com/...",
    metadata: {
      usage: "Service Icon - Structural Engineering",
      category: "services",
      tags: "icon,structural,engineering",
      usedIn: "services-section",
    },
  },
  {
    name: "services/electrical-systems-icon.svg",
    bucket: "ptr-command-center-assets",
    generation: "1738945811000",
    metageneration: "1",
    contentType: "image/svg+xml",
    timeCreated: "2026-01-20T15:05:00.000Z",
    updated: "2026-01-20T15:05:00.000Z",
    storageClass: "STANDARD",
    size: "38912", // 38 KB in bytes
    md5Hash: "4f3e2d1c0b9a...",
    mediaLink: "https://firebasestorage.googleapis.com/...",
    metadata: {
      usage: "Service Icon - Electrical Systems",
      category: "services",
      tags: "icon,electrical,systems",
      usedIn: "services-section",
    },
  },

  // Certificates
  {
    name: "certificates/iso-certification.pdf",
    bucket: "ptr-command-center-assets",
    generation: "1738945812000",
    metageneration: "1",
    contentType: "application/pdf",
    timeCreated: "2026-01-08T14:45:00.000Z",
    updated: "2026-01-08T14:45:00.000Z",
    storageClass: "STANDARD",
    size: "1887436", // 1.8 MB in bytes
    md5Hash: "8g7f6e5d4c3b...",
    mediaLink: "https://firebasestorage.googleapis.com/...",
    metadata: {
      usage: "ISO 9001 Certification",
      category: "certificates",
      tags: "iso,certification,quality",
      usedIn: "about-page,credentials",
    },
  },

  // Documentation
  {
    name: "documents/company-profile.pdf",
    bucket: "ptr-command-center-assets",
    generation: "1738945813000",
    metageneration: "1",
    contentType: "application/pdf",
    timeCreated: "2026-01-03T09:00:00.000Z",
    updated: "2026-01-03T09:00:00.000Z",
    storageClass: "STANDARD",
    size: "3565158", // 3.4 MB in bytes
    md5Hash: "2h1g0f9e8d7c...",
    mediaLink: "https://firebasestorage.googleapis.com/...",
    metadata: {
      usage: "Company Profile Document",
      category: "documents",
      tags: "profile,company,overview",
      usedIn: "downloads,proposals",
    },
  },
  {
    name: "documents/capabilities-statement.pdf",
    bucket: "ptr-command-center-assets",
    generation: "1738945814000",
    metageneration: "1",
    contentType: "application/pdf",
    timeCreated: "2026-01-03T09:30:00.000Z",
    updated: "2026-01-03T09:30:00.000Z",
    storageClass: "STANDARD",
    size: "3040870", // 2.9 MB in bytes
    md5Hash: "9i8h7g6f5e4d...",
    mediaLink: "https://firebasestorage.googleapis.com/...",
    metadata: {
      usage: "Capabilities Statement",
      category: "documents",
      tags: "capabilities,statement,services",
      usedIn: "proposals,bids",
    },
  },
];

export const getMediaAssets = () => sampleProcessedAssets;
